apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: kubernetes-csi-addons
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager-metrics-service
  namespace: system
spec:
  ports:
    - name: http
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    control-plane: controller-manager
